export { default as Hero } from './_hero'
export { default as Projects } from './_projects'
export { default as About } from './_about'
export { default as Contact } from './_contact'
export { default as ParallaxPage } from './_paralax'
