export const GatsbyGraph = {
	nodes: [
		{ id: 'JavaScript', group: 3 },
		{ id: 'TypeScript', group: 4 },
		{ id: 'Node.js', group: 3 },
		{ id: 'Express.js', group: 3 },
		{ id: 'D3.js', group: 3 },
		{ id: 'Angular NGX', group: 4 },
		{ id: 'RxJS', group: 6 },
		{ id: 'Gatsby.js', group: 1 },
		{ id: 'Next.js', group: 1 },
		{ id: 'React.js', group: 3 },
		{ id: 'GraphQL', group: 2 },
		{ id: 'Redux', group: 6 },
		{ id: 'ReduxJS Toolkit', group: 6 },
		{ id: 'Firebase', group: 5 },
		{ id: 'Firebase/Auth', group: 5 },
		{ id: 'Firebase/Database', group: 5 },
		{ id: 'Firebase/Firestore', group: 5 },
		{ id: 'Firebase/Functions', group: 5 },
		{ id: 'AngularFire2', group: 4 },
		{ id: 'Material UI', group: 3 },
		{ id: 'JavaScript Styles/JSS', group: 3 },
		{ id: 'Styled Components', group: 3 },
		{ id: 'Emotion CSS', group: 3 },
		{ id: 'Tailwind CSS', group: 3 },
	],
	links: [
		{ source: 'Gatsby.js', target: 'GraphQL', value: 8 },
		{ source: 'Gatsby.js', target: 'Next.js', value: 8 },
		{ source: 'Gatsby.js', target: 'React.js', value: 8 },
		{ source: 'Gatsby.js', target: 'JavaScript', value: 8 },
		{ source: 'Gatsby.js', target: 'TypeScript', value: 8 },
		{ source: 'Gatsby.js', target: 'Redux', value: 8 },
		{ source: 'Gatsby.js', target: 'Material UI', value: 8 },
		{ source: 'Gatsby.js', target: 'Styled Components', value: 8 },
		{ source: 'Gatsby.js', target: 'Firebase', value: 8 },
		{ source: 'Gatsby.js', target: 'Tailwind CSS', value: 8 },
		{ source: 'Gatsby.js', target: 'Emotion CSS', value: 8 },
		{ source: 'Gatsby.js', target: 'Node.js', value: 8 },
	],
};
